fix(import): fail to import CRD without a schema (#417)
Following https://github.com/cdk8s-team/cdk8s-cli/pull/404, CRD's that don't have a schema are failing to import. 

```console
Error: Schema for version v1alpha1 is missing
```

While it doesn't really make sense for a CRD not to have a schema, it was technically allowed in earlier versions of k8s. From kubernetes [docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/):

*With apiextensions.k8s.io/v1 the definition of a structural schema is mandatory for CustomResourceDefinitions. In the beta version of CustomResourceDefinition, the structural schema was optional.*

This means that https://github.com/cdk8s-team/cdk8s-cli/pull/404 introduced a breaking change by mistake. 

This PR removes the assertion on non empty schemas, like it was before.